Create a search that based on many paramenters
Caovietbach/QTSV pull request #6
Opened 2024-07-25 09:36 UTC by Caovietbach

2024-07-25 10:32 UTC, chitoan19 requested changes

2024-07-25 10:32 UTC, chitoan19 commented on src/main/java/org/example/qtsv/service/StudentService.java
> +        List<Student> studentsList = listAll();
ko dùng hàm findAll mặc định của JPA, 
viết query theo các điều kiện để hạn chế dữ liệu trả về từ database

2024-07-25 10:32 UTC, chitoan19 commented on src/main/java/org/example/qtsv/service/StudentService.java
> +        List<Student> allStudents = listAll();
duplicate code: List<Student> allStudents = listAll(); ở các hàm sortBy

2024-07-25 10:32 UTC, chitoan19 commented on src/main/java/org/example/qtsv/service/StudentService.java
> +        List<Student> allStudents = listAll();
duplicate code: List<Student> allStudents = listAll(); ở các hàm sortBy

2024-07-25 10:32 UTC, chitoan19 commented on src/main/java/org/example/qtsv/service/StudentService.java
> +        List<Student> allStudents = listAll();
duplicate code: List<Student> allStudents = listAll(); ở các hàm sortBy

2024-07-25 10:32 UTC, chitoan19 commented on src/main/java/org/example/qtsv/service/StudentService.java
> +        List<Student> allStudents = listAll();
duplicate code: List<Student> allStudents = listAll(); ở các hàm sortBy

2024-07-25 10:32 UTC, chitoan19 commented on src/main/java/org/example/qtsv/controller/StudentControllerNew.java
> +        sortStudents = service.listAll();
ở đây listAll student rồi trong các hàm bên dưới lại có listAll lần nữa ?
service.sortByLastYear(), 
service.sortByLastYearAndCountry()
,service.sortByGPAFromHighToLow(),
service.sortByGPAFromHighToLowAndLastName(), 
service.search()

2024-07-25 10:32 UTC, chitoan19 commented on src/main/java/org/example/qtsv/controller/StudentControllerNew.java
> +                                         @RequestParam(value = "major", required = false) String major, @RequestParam(value = "country", required = false) String country){
ở đây dùng @RequestParam riêng lẻ cho từng field -> nếu có nhiều field thì rất rối
có thể gộp lại thành 1 object đc ko?

2024-07-25 10:32 UTC, chitoan19 commented on src/main/java/org/example/qtsv/controller/StudentControllerNew.java
> +        Student existingStudent = service.get(id);
các bước xử lý logic nên viết ra hàm riêng để ở service, controller chỉ gọi tới hàm đó để trả về kết quả

2024-08-01 02:48 UTC, Caovietbach commented on src/main/java/org/example/qtsv/service/StudentService.java
> +        List<Student> allStudents = listAll();
Đã Fix

2024-08-01 02:48 UTC, Caovietbach commented on src/main/java/org/example/qtsv/service/StudentService.java
> +        List<Student> allStudents = listAll();
Đã fix

2024-08-01 02:48 UTC, Caovietbach commented on src/main/java/org/example/qtsv/service/StudentService.java
> +        List<Student> allStudents = listAll();
Đã fix

2024-08-01 02:49 UTC, Caovietbach commented on src/main/java/org/example/qtsv/controller/StudentControllerNew.java
> +        sortStudents = service.listAll();
Đã fix

2024-08-01 02:50 UTC, Caovietbach commented on src/main/java/org/example/qtsv/controller/StudentControllerNew.java
> +                                         @RequestParam(value = "major", required = false) String major, @RequestParam(value = "country", required = false) String country){
Đã dùng Object để thay thế

2024-08-01 02:50 UTC, Caovietbach commented on src/main/java/org/example/qtsv/controller/StudentControllerNew.java
> +        Student existingStudent = service.get(id);
Đã chuyển edit function sang Service.

2024-08-01 02:51 UTC, chitoan19 requested changes

2024-08-01 02:51 UTC, chitoan19 commented on src/main/java/org/example/qtsv/service/StudentService.java
>      public String validateNewInformation(Student student){
validateNewInformation(), validateEditInformation(), 2 function xử lý giống nhau

2024-08-01 02:51 UTC, chitoan19 commented on src/main/java/org/example/qtsv/service/StudentService.java
> +                .filter(s -> s.getYear() == 4)
chưa thực hiện sắp xếp ở đây
year filter theo param truyền vào nhưng ở đây luôn filter year = 4 ?

2024-08-01 02:51 UTC, chitoan19 commented on src/main/java/org/example/qtsv/service/StudentService.java
> +                .filter(s -> s.getYear() == 4 && "Ha Noi".equals(s.getCountry()))
chưa thực hiện sắp xếp ở đây
year, country filter theo param truyền vào nhưng ở đây luôn filter year = 4 và country = "Ha Noi" ?

2024-08-01 02:51 UTC, chitoan19 commented on src/main/java/org/example/qtsv/service/StudentService.java
> +    public List<Student> search( Student student, List<Student> allStudents){
chưa viết query để filter giới hạn kết quả trả về từ database

2024-08-01 03:14 UTC, Caovietbach commented on src/main/java/org/example/qtsv/service/StudentService.java
> +                .filter(s -> s.getYear() == 4 && "Ha Noi".equals(s.getCountry()))
Cái này là do đề bài là lọc dựa vào sinh viên năm cuối và quê là ở Hà Nội. Lúc trước em để năm cuối của sinh viên mặc định là 4.

2024-08-01 03:14 UTC, Caovietbach commented on src/main/java/org/example/qtsv/service/StudentService.java
> +                .filter(s -> s.getYear() == 4)
Cái này là do đề bài là lọc dựa vào sinh viên năm cuối. Lúc trước em để năm cuối của sinh viên mặc định là 4.

2024-08-02 06:48 UTC, Caovietbach commented on src/main/java/org/example/qtsv/service/StudentService.java
>      public String validateNewInformation(Student student){
Em sửa rồi ạ.

2024-09-19 09:02 UTC, closed without merging